name: Build and Deploy

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: yarn install
      - run: yarn build
      - uses: actions/upload-artifact@master
        with:
          name: build files
          path: dist/